[package]
name = "api"
version = "0.1.0"
authors = ["haato3o <me@haato.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
domain = { path = "../domain" }
data = { path = "../data" }